### ISSUE TITLE
Difficulties when trying to install develop branch

### ISSUE THREAD

**Issue by laagland** [tinesoft/ngx-cookieconsent#113]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.1
- ngx-cookieconsent version: develop branch
```

### OS Version?
node14-alpine on WSL2 Windows10

### Angular, Node and al Versions?
angular 12.1.1
node 14.17.1

### Repro steps
npm i https://github.com/tinesoft/ngx-cookieconsent#develop in an angular project

I'm trying to install the develop branch of this package to get the latest updates, but I keep getting "Cannot find module 'ngx-cookieconsent' or its corresponding type declarations.ts(2307)" when trying to import from ngx-cookieconsent in my main angular module.

Am I missing something obvious here?

**Comment by tinesoft** [comment]
Hi @laagland 

The library need to be built and distributed as an  Angular library, so that you can use it in your app... Referencing the dev branch will not work as it doesn't contain such build, just the raw project.


I'm finishing up a few additional features... I should release the latest version soon.  Stay tuned!
