### ISSUE TITLE
Readme Instruction for Modifying Text/Links Outdated

### ISSUE THREAD

**Issue by 360disrupt** [tinesoft/ngx-cookieconsent#47]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
```
Related issue: [Is it possible to include multiple links and insert them in the middle of a sentence?](https://github.com/tinesoft/ngx-cookieconsent/issues/43)

### CookieConsent and Library Versions?
```
- ngx-cookieconsent version:2.2.0
```

### Repro steps
Use code example from the readme.

### The log given by the failure
```
ERROR in src/app/app.module.ts(66,5): error TS2322: Type '{ message: string; privacyPolicyLink: string; privacyPolicyHref: string; tosLink: string; tosHref: string; }' is not assignable to type 'NgcContentOptions'.
  Object literal may only specify known properties, and 'privacyPolicyLink' does not exist in type 'NgcContentOptions'.
```

### Desired functionality
Readme example compatible with types.

### Mention any other details that might be useful
E.g. `Readme.md` `messageLink` (camel case) in the types: `messagelink` (lower case)
[html-elements.ts](https://github.com/tinesoft/ngx-cookieconsent/blob/master/src/model/html-elements.ts#L11)

Also content options does not have any of these props:
```
    cookiePolicyLink: 'Cookie Policy',
    cookiePolicyHref: 'https://cookie.com',

    privacyPolicyLink: 'Privacy Policy',
    privacyPolicyHref: 'https://privacy.com',

    tosLink: 'Terms of Service',
    tosHref: 'https://tos.com',
```
[content-options.ts](https://github.com/tinesoft/ngx-cookieconsent/blob/master/src/model/content-options.ts)

**Comment by tinesoft** [comment]
Hi @360disrupt 

Thanks for your issue

> The log given by the failure
> ```
> ERROR in src/app/app.module.ts(66,5): error TS2322: Type '{ message: string; privacyPolicyLink: string; privacyPolicyHref: string; tosLink: string; tosHref: string; }' is not assignable to type 'NgcContentOptions'.
>   Object literal may only specify known properties, and 'privacyPolicyLink' does not exist in type 'NgcContentOptions'.
> ```
> 
This error seems to indicate that somehow, you are still referencing an old version of `ngx-cookieconsent` (prior to v2.2.0) because [v2.2.0](https://github.com/tinesoft/ngx-cookieconsent/releases)  introduced [changes](https://github.com/tinesoft/ngx-cookieconsent/commit/4b32ce0) that made it possible to use custom properties in both `NgcContentOptions` and `NgcHTMLElements` (via the catchall property `[key: string]: string;`)

So please, make sure that:
- you use `ngx-cookieconsent@2.2.0` in `package.json`
- `rm -rf node_modules`
- `npm install`
- test again

> E.g. Readme.md messageLink (camel case) in the types: messagelink (lower case)
> html-elements.ts 
Based on what i said above, this will work nonetheless (because of the catchall property). But for clarity, i aligned the README.
