### ISSUE TITLE
Cookie notification showing up after every refresh (IE)

### ISSUE THREAD

**Issue by jarthur247** [tinesoft/ngx-cookieconsent#48]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.0
- ngx-cookieconsent version: 2.1.1
```

### OS Version?
> Windows 10

### Angular and Node versions
```
- Angular CLI: 7.3.6
- Node: 8.11.3  
- Angular: 7.2.9   
```

### Repro steps
Exactly the same as https://github.com/insites/cookieconsent/issues/139 but for ngx-cookieconsent rather than cookieconsent. However, ignoreDoNotTrack is not a property of NgcCookieConsentConfig and so I cannot apply the same fix.

**Comment by tinesoft** [comment]
Hi @jarthur247 

Thanks for your ticket, but i'm afraid the solution mentioned in the link , i.e. setting a `ignoreDoNotTrack`  does not work. In fact, there is no such property in original [CookieConsent code](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js) itself (`NgcCookieConsentConfig` is just type definition for the config in the original library).

For me, this is rather a setting _that must be activated in your IE browser directly_, because it is preventing `cookieconsent`  to set the **status** cookie that indicates whether or not user has already dismissed the cookie bar.
